### ISSUE TITLE
Create Visualization Objects to Answer North American Trade Question / Story:

### ISSUE THREAD

**Issue by tuneman7** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#17]
North American Trade:
Is there a link between NAFTA trading partners and increased GDP with NAFTA trading partner nations?
What percentage of trade is driven by services?
What percentage of trade is driven by merchandise?

**Comment by tuneman7** [comment]
Note 03/17/2022. In progress.  To be completed by Sat 03/19/2022

**Comment by jpdc23** [comment]
Updated North American Trade section with Overview of North America trade across the world and with other continents.
Added story for NAFTA country trade with continents and countries across the world.
Added story for NAFTA impact including Top import and export sectors. Took out the services and trades to add GDP growth and Unemployment.

For post usability would like to update import and export to possibly use a pie chart or one of Amber's charts.

**Comment by jpdc23** [comment]
Need to evaluate continental trade partners ranks as I do not see Iran.

**Comment by tuneman7** [comment]
Closed.
