### ISSUE TITLE
Change Year Slider into the top right corner -- China

### ISSUE THREAD

**Issue by tuneman7** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#30]
<img width="694" alt="Screen Shot 2022-03-09 at 1 35 30 PM" src="https://user-images.githubusercontent.com/81119979/157540268-8da487e3-46d5-458c-9f12-56bcf048dede.png">

**Comment by ShuYingAmberChen** [comment]
Andy Reagan posted a solution: https://stackoverflow.com/questions/62103632/altair-change-the-position-of-a-slider

**Comment by tuneman7** [comment]
Completed.
