### ISSUE TITLE
Fix 3rd NAFTA Slide so that whitespace is not present in graph. 

### ISSUE THREAD

**Issue by tuneman7** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#37]
![Screen Shot 2022-03-26 at 9 05 14 AM](https://user-images.githubusercontent.com/81119979/160247835-26c7b944-70d9-4612-a68b-423e04fb4c81.png)

**Comment by jpdc23** [comment]
Fixed issue, each slide has a legend and should render in a better format.
