### ISSUE TITLE
replace the fourth quadrant to show how much a source country imports and exports to a target country

### ISSUE THREAD

**Issue by ShuYingAmberChen** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#43]
In 2020 did the United States import more to the Netherlands or export more to the Netherlands?
![image](https://user-images.githubusercontent.com/59714221/161169688-d280903e-92fb-44e5-8f5f-19d3c31bb106.png)

**Comment by tuneman7** [comment]
Leave for now.
