### ISSUE TITLE
Update tooltip to explicitly show trade with NAFTA/external 

### ISSUE THREAD

**Issue by ShuYingAmberChen** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#46]
In 2020 what percentage of NAFTA’s trade was external, and what percentage was within the NAFTA trading bloc?
![image](https://user-images.githubusercontent.com/59714221/161170523-92d66629-3eb2-4056-a330-780289059182.png)

**Comment by jpdc23** [comment]
Updated slide to only include 2 charts showing NAFTA continental trade which provides a similar snapshot.

**Comment by jpdc23** [comment]
Updated chart
