### ISSUE TITLE
NAFTA charts Key NaN, titles do not change

### ISSUE THREAD

**Issue by ShuYingAmberChen** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#47]
![image](https://user-images.githubusercontent.com/59714221/161170820-2c3e3bb7-34a7-43ef-860b-a4349ce6330b.png)

**Comment by jpdc23** [comment]
Currently have this chart removed to simplify pages.

**Comment by jpdc23** [comment]
Updated Chart in case we want to add it back in

![image](https://user-images.githubusercontent.com/29155868/161754930-8b3cd4b0-6106-4d0d-84cc-bcf46062032e.png)
