### ISSUE TITLE
users are confused with the second country dropdown; explore slider label

### ISSUE THREAD

**Issue by ShuYingAmberChen** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#48]
![image](https://user-images.githubusercontent.com/59714221/161170978-e1122949-f97e-48da-86c1-ca1fb7c305df.png)

**Comment by jpdc23** [comment]
Updated slides 2 and 3 to include only 2 charts. This eliminated the duplicate drop downs.

**Comment by jpdc23** [comment]
Removed with new layout
