### ISSUE TITLE
GDP chart: local currency

### ISSUE THREAD

**Issue by ShuYingAmberChen** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#49]
No one was able to answer local currency correctly.
The secondary drop down not needed.
![image](https://user-images.githubusercontent.com/59714221/161171317-9d4595d3-4878-41e3-898a-08c4cedb506c.png)

**Comment by jpdc23** [comment]
Currently removed GDP per Capita Local Currency unit chart as it was confusing to the users. Kept GDP growth and added highlighter.

**Comment by tuneman7** [comment]
Closed no longer using.
