### ISSUE TITLE
EU vs non-EU country differentiation

### ISSUE THREAD

**Issue by ShuYingAmberChen** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#50]
For the year 2020, which non-EU country has the largest trade percentage with the EU?
People didn't know which countries were EU or not.
![image](https://user-images.githubusercontent.com/59714221/161171386-7fa62e84-f606-4d09-b738-3eb22827d603.png)

**Comment by tuneman7** [comment]
Stan to close this out.

**Comment by tuneman7** [comment]
Stan needs to close this out and put images of the before and after stuff. ...

**Comment by fzhang007** [comment]
![Screen Shot 2022-04-13 at 10 14 42 PM](https://user-images.githubusercontent.com/77035634/163300599-ec7c191f-0fe6-4c41-9fa8-73eb11814613.png)
