### ISSUE TITLE
Modify Trade by source and target nation graph to have stronger lines, and modify legend.

### ISSUE THREAD

**Issue by tuneman7** [tuneman7/w209_spring_2022_thu_4_pm_team_4_web#7]

**Comment by tuneman7** [comment]
Format Numbers, make lines stronger, etc. ...
![Screen Shot 2022-03-01 at 6 39 18 AM](https://user-images.githubusercontent.com/81119979/156189152-5dd84ff0-cb99-45ec-8590-e197ab6eba23.png)

**Comment by tuneman7** [comment]
To Amber to close if needed or refine as needed.

**Comment by ShuYingAmberChen** [comment]
![image](https://user-images.githubusercontent.com/59714221/159124375-aeae9ddc-dfde-4151-9333-0108b0be6414.png)
